### ISSUE TITLE
[Bug] crash with botany pots.

### ISSUE THREAD

**Issue by AlienXtream** [joshiejack/Horticulture#1]
game fails to load Horticulture module with botany pots 1.16.5-7.0.27 (aka, release version as of writing this)

[crash-2021-06-29_19.55.36-fml.txt](https://github.com/Harvest-Festival/Horticulture/files/6732469/crash-2021-06-29_19.55.36-fml.txt)

this is a minor problem as most people will just download the release version automatically and not check the alpha/betas. as such many people will be reporting an issue when there technically isn't one. if possible to add some sort of message to the crash report if the version is too low or add BP as a required dependency?

**Comment by joshiejack** [comment]
You need to update botany pots.

**Comment by AlienXtream** [comment]
yeh, lol. i was mid updating the report when you replied XD

**Comment by joshiejack** [comment]
Yeah I saw :P

**Comment by joshiejack** [comment]
The crash is actually with Simply Seasons btw =P

**Comment by AlienXtream** [comment]
oh, yeh. ofc. thats the one that has the compat. duh... well, indicating the need for a min version of BP would be a good idea. glad to see this one making a return for 1.16. i will be sure to make many posts on bugs and incompatibilities as im running 416 mods (and counting). good news is that if it works for me it should work with most other mods :P

**Comment by joshiejack** [comment]
At my pace probably more like months. Although some bits would come quicker since they're not as complicated. I'd expect the shops and stuff to take me a little while to update. The parts I want to work on after at least part of it shouldn't take too long. I expect updating the npcs,quests and stuff will take me the longest :p. But I can't really predict. Since my mood changes a lot xD.
